name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Nextcloud version
        id: ncver
        run: |
          docker run --rm debian:12-slim \
            sh -c "apt-get update -qq && \
                   apt-get install -yqq wget gnupg2 ca-certificates && \
                   wget -qO - https://download.opensuse.org/repositories/home:nextcloud/Debian_12/Release.key | gpg --dearmor > /usr/share/keyrings/nextcloud.gpg && \
                   echo 'deb [signed-by=/usr/share/keyrings/nextcloud.gpg] https://download.opensuse.org/repositories/home:/nextcloud/Debian_12/ /' > /etc/apt/sources.list.d/nextcloud.list && \
                   apt-get update -qq && \
                   apt-cache policy nextcloud-desktop | grep Candidate | awk '{print \$2}'" \
            > version.txt
          echo "ncversion=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-client:${{ steps.ncver.outputs.ncversion }}
            ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-client:${{ github.sha }}
